### ISSUE TITLE
Crash android.media.MediaCodec$CodecException: Error 0xffffffde

### ISSUE THREAD

**Issue by dereklawrence** [ChillingVan/AndroidInstantVideo#11]
E/AndroidRuntime: FATAL EXCEPTION: WriteVideoHandlerThread
    Process: com.test, PID: 20720
    Theme: themes:{default=overlay:system, iconPack:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}
    android.media.MediaCodec$CodecException: Error 0xffffffde
        at android.media.MediaCodec.releaseOutputBuffer(Native Method)
        at android.media.MediaCodec.releaseOutputBuffer(MediaCodec.java:2424)
        at com.test.encoder.MediaCodecInputStream.read(MediaCodecInputStream.java:112)
        at com.test.encoder.MediaCodecInputStream.readAll(MediaCodecInputStream.java:136)
        at com.test.publisher.StreamPublisher$2.handleMessage(StreamPublisher.java:116)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)

This occurs frequently but not always

**Comment by ChillingVan** [comment]
Can it be replicated in the samples? How to trigger it?

**Comment by inventionsbyhamid** [comment]
+1 I also encountered this and I have still not been able to reproduce this in sample. Any idea or direction why this might occur? Have you been able to solve this? @dereklawrence

**Comment by jinyingfeng** [comment]
我也遇到这个问题，加个try catch 就可以了
