### ISSUE TITLE
TestCameraAndVideoActivity - does it record in video file?

### ISSUE THREAD

**Issue by anonym24** [ChillingVan/AndroidInstantVideo#15]
I tried TestCameraAndVideoActivity sample, but what does it do? Does it write to file? I could find this video file

![screenshot_2018-07-22-13-58-54-582_com chillingvan instantvideo sample](https://user-images.githubusercontent.com/8851301/43044911-8e9009c6-8db7-11e8-8f9d-410477f9c576.png)

Also it has many exceptions when I press "Stop" button, mb it fails to create file and record something to it

```
07-22 13:53:47.774 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
    java.io.IOException: This InputStream was closed
        at com.chillingvan.lib.encoder.MediaCodecInputStream.read(MediaCodecInputStream.java:108)
        at com.chillingvan.lib.encoder.MediaCodecInputStream.readAll(MediaCodecInputStream.java:138)
        at com.chillingvan.lib.publisher.StreamPublisher$2.handleMessage(StreamPublisher.java:116)
        at android.os.Handler.dispatchMessage(Handler.java:102)
07-22 13:53:47.775 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at android.os.Looper.loop(Looper.java:157)
        at android.os.HandlerThread.run(HandlerThread.java:61)
    java.io.IOException: This InputStream was closed
        at com.chillingvan.lib.encoder.MediaCodecInputStream.read(MediaCodecInputStream.java:108)
        at com.chillingvan.lib.encoder.MediaCodecInputStream.readAll(MediaCodecInputStream.java:138)
        at com.chillingvan.lib.publisher.StreamPublisher$2.handleMessage(StreamPublisher.java:116)
        at android.os.Handler.dispatchMessage(Handler.java:102)
07-22 13:53:47.776 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at android.os.Looper.loop(Looper.java:157)
        at android.os.HandlerThread.run(HandlerThread.java:61)
    java.io.IOException: This InputStream was closed
        at com.chillingvan.lib.encoder.MediaCodecInputStream.read(MediaCodecInputStream.java:108)
        at com.chillingvan.lib.encoder.MediaCodecInputStream.readAll(MediaCodecInputStream.java:138)
        at com.chillingvan.lib.publisher.StreamPublisher$2.handleMessage(StreamPublisher.java:116)
        at android.os.Handler.dispatchMessage(Handler.java:102)
07-22 13:53:47.777 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at android.os.Looper.loop(Looper.java:157)
        at android.os.HandlerThread.run(HandlerThread.java:61)
    java.io.IOException: This InputStream was closed
        at com.chillingvan.lib.encoder.MediaCodecInputStream.read(MediaCodecInputStream.java:108)
        at com.chillingvan.lib.encoder.MediaCodecInputStream.readAll(MediaCodecInputStream.java:138)
        at com.chillingvan.lib.publisher.StreamPublisher$2.handleMessage(StreamPublisher.java:116)
07-22 13:53:47.778 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.os.HandlerThread.run(HandlerThread.java:61)
    java.io.IOException: This InputStream was closed
        at com.chillingvan.lib.encoder.MediaCodecInputStream.read(MediaCodecInputStream.java:108)
        at com.chillingvan.lib.encoder.MediaCodecInputStream.readAll(MediaCodecInputStream.java:138)
        at com.chillingvan.lib.publisher.StreamPublisher$2.handleMessage(StreamPublisher.java:116)
07-22 13:53:47.779 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.os.HandlerThread.run(HandlerThread.java:61)
    java.io.IOException: This InputStream was closed
        at com.chillingvan.lib.encoder.MediaCodecInputStream.read(MediaCodecInputStream.java:108)
        at com.chillingvan.lib.encoder.MediaCodecInputStream.readAll(MediaCodecInputStream.java:138)
07-22 13:53:47.780 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at com.chillingvan.lib.publisher.StreamPublisher$2.handleMessage(StreamPublisher.java:116)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.os.HandlerThread.run(HandlerThread.java:61)
    java.io.IOException: This InputStream was closed
        at com.chillingvan.lib.encoder.MediaCodecInputStream.read(MediaCodecInputStream.java:108)
        at com.chillingvan.lib.encoder.MediaCodecInputStream.readAll(MediaCodecInputStream.java:138)
07-22 13:53:47.781 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at com.chillingvan.lib.publisher.StreamPublisher$2.handleMessage(StreamPublisher.java:116)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.os.HandlerThread.run(HandlerThread.java:61)
    java.io.IOException: This InputStream was closed
        at com.chillingvan.lib.encoder.MediaCodecInputStream.read(MediaCodecInputStream.java:108)
        at com.chillingvan.lib.encoder.MediaCodecInputStream.readAll(MediaCodecInputStream.java:138)
07-22 13:53:47.782 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at com.chillingvan.lib.publisher.StreamPublisher$2.handleMessage(StreamPublisher.java:116)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.os.HandlerThread.run(HandlerThread.java:61)
    java.io.IOException: This InputStream was closed
        at com.chillingvan.lib.encoder.MediaCodecInputStream.read(MediaCodecInputStream.java:108)
07-22 13:53:47.783 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at com.chillingvan.lib.encoder.MediaCodecInputStream.readAll(MediaCodecInputStream.java:138)
        at com.chillingvan.lib.publisher.StreamPublisher$2.handleMessage(StreamPublisher.java:116)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.os.HandlerThread.run(HandlerThread.java:61)
    java.io.IOException: This InputStream was closed
        at com.chillingvan.lib.encoder.MediaCodecInputStream.read(MediaCodecInputStream.java:108)
07-22 13:53:47.784 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at com.chillingvan.lib.encoder.MediaCodecInputStream.readAll(MediaCodecInputStream.java:138)
        at com.chillingvan.lib.publisher.StreamPublisher$2.handleMessage(StreamPublisher.java:116)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.os.HandlerThread.run(HandlerThread.java:61)
    java.io.IOException: This InputStream was closed
07-22 13:53:47.785 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at com.chillingvan.lib.encoder.MediaCodecInputStream.read(MediaCodecInputStream.java:108)
        at com.chillingvan.lib.encoder.MediaCodecInputStream.readAll(MediaCodecInputStream.java:138)
        at com.chillingvan.lib.publisher.StreamPublisher$2.handleMessage(StreamPublisher.java:116)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.os.HandlerThread.run(HandlerThread.java:61)
    java.io.IOException: This InputStream was closed
07-22 13:53:47.786 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at com.chillingvan.lib.encoder.MediaCodecInputStream.readAll(MediaCodecInputStream.java:138)
        at android.os.HandlerThread.run(HandlerThread.java:61)
07-22 13:53:47.789 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at com.chillingvan.lib.encoder.MediaCodecInputStream.read(MediaCodecInputStream.java:108)
07-22 13:53:47.790 32261-408/com.chillingvan.instantvideo.sample W/System.err: java.io.IOException: This InputStream was closed
        at com.chillingvan.lib.encoder.MediaCodecInputStream.readAll(MediaCodecInputStream.java:138)
07-22 13:53:47.791 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
07-22 13:53:47.792 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-22 13:53:47.793 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at com.chillingvan.lib.publisher.StreamPublisher$2.handleMessage(StreamPublisher.java:116)
07-22 13:53:47.794 32261-408/com.chillingvan.instantvideo.sample W/System.err: java.io.IOException: This InputStream was closed
        at com.chillingvan.lib.encoder.MediaCodecInputStream.readAll(MediaCodecInputStream.java:138)
07-22 13:53:47.795 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
07-22 13:53:47.796 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-22 13:53:47.798 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at com.chillingvan.lib.publisher.StreamPublisher$2.handleMessage(StreamPublisher.java:116)
    java.io.IOException: This InputStream was closed
        at com.chillingvan.lib.encoder.MediaCodecInputStream.readAll(MediaCodecInputStream.java:138)
07-22 13:53:47.799 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
        at com.chillingvan.lib.publisher.StreamPublisher$2.handleMessage(StreamPublisher.java:116)
07-22 13:53:47.800 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
        at com.chillingvan.lib.encoder.MediaCodecInputStream.readAll(MediaCodecInputStream.java:138)
07-22 13:53:47.801 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at com.chillingvan.lib.encoder.MediaCodecInputStream.readAll(MediaCodecInputStream.java:138)
07-22 13:53:47.802 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at com.chillingvan.lib.encoder.MediaCodecInputStream.read(MediaCodecInputStream.java:108)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.os.HandlerThread.run(HandlerThread.java:61)
07-22 13:53:47.803 32261-408/com.chillingvan.instantvideo.sample W/System.err: java.io.IOException: This InputStream was closed
        at com.chillingvan.lib.encoder.MediaCodecInputStream.read(MediaCodecInputStream.java:108)
        at com.chillingvan.lib.encoder.MediaCodecInputStream.readAll(MediaCodecInputStream.java:138)
        at com.chillingvan.lib.publisher.StreamPublisher$2.handleMessage(StreamPublisher.java:116)
        at android.os.Looper.loop(Looper.java:157)
        at com.chillingvan.lib.publisher.StreamPublisher$2.handleMessage(StreamPublisher.java:116)
07-22 13:53:47.804 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
        at com.chillingvan.lib.encoder.MediaCodecInputStream.read(MediaCodecInputStream.java:108)
        at android.os.Handler.dispatchMessage(Handler.java:102)
07-22 13:53:47.805 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at com.chillingvan.lib.publisher.StreamPublisher$2.handleMessage(StreamPublisher.java:116)
    java.io.IOException: This InputStream was closed
07-22 13:53:47.806 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-22 13:53:47.807 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at com.chillingvan.lib.encoder.MediaCodecInputStream.readAll(MediaCodecInputStream.java:138)
        at android.os.HandlerThread.run(HandlerThread.java:61)
07-22 13:53:47.808 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at com.chillingvan.lib.publisher.StreamPublisher$2.handleMessage(StreamPublisher.java:116)
    java.io.IOException: This InputStream was closed
07-22 13:53:47.809 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
07-22 13:53:47.810 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at com.chillingvan.lib.encoder.MediaCodecInputStream.read(MediaCodecInputStream.java:108)
        at com.chillingvan.lib.encoder.MediaCodecInputStream.readAll(MediaCodecInputStream.java:138)
07-22 13:53:47.811 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at com.chillingvan.lib.publisher.StreamPublisher$2.handleMessage(StreamPublisher.java:116)
    java.io.IOException: This InputStream was closed
        at android.os.Handler.dispatchMessage(Handler.java:102)
07-22 13:53:47.812 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at android.os.Looper.loop(Looper.java:157)
07-22 13:53:47.813 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at com.chillingvan.lib.publisher.StreamPublisher$2.handleMessage(StreamPublisher.java:116)
    java.io.IOException: This InputStream was closed
        at com.chillingvan.lib.encoder.MediaCodecInputStream.readAll(MediaCodecInputStream.java:138)
        at android.os.Looper.loop(Looper.java:157)
07-22 13:53:47.814 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at com.chillingvan.lib.encoder.MediaCodecInputStream.read(MediaCodecInputStream.java:108)
        at com.chillingvan.lib.encoder.MediaCodecInputStream.readAll(MediaCodecInputStream.java:138)
07-22 13:53:47.815 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at com.chillingvan.lib.publisher.StreamPublisher$2.handleMessage(StreamPublisher.java:116)
07-22 13:53:47.816 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
        at com.chillingvan.lib.encoder.MediaCodecInputStream.read(MediaCodecInputStream.java:108)
07-22 13:53:47.817 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at com.chillingvan.lib.encoder.MediaCodecInputStream.readAll(MediaCodecInputStream.java:138)
07-22 13:53:47.818 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
        at com.chillingvan.lib.encoder.MediaCodecInputStream.read(MediaCodecInputStream.java:108)
07-22 13:53:47.819 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at com.chillingvan.lib.encoder.MediaCodecInputStream.read(MediaCodecInputStream.java:108)
        at android.os.HandlerThread.run(HandlerThread.java:61)
07-22 13:53:47.820 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at com.chillingvan.lib.encoder.MediaCodecInputStream.read(MediaCodecInputStream.java:108)
        at android.os.HandlerThread.run(HandlerThread.java:61)
    java.io.IOException: This InputStream was closed
07-22 13:53:47.821 32261-408/com.chillingvan.instantvideo.sample W/System.err: java.io.IOException: This InputStream was closed
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at com.chillingvan.lib.encoder.MediaCodecInputStream.read(MediaCodecInputStream.java:108)
07-22 13:53:47.822 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
07-22 13:53:47.823 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
        at com.chillingvan.lib.encoder.MediaCodecInputStream.read(MediaCodecInputStream.java:108)
07-22 13:53:47.824 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
    java.io.IOException: This InputStream was closed
07-22 13:53:47.825 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at com.chillingvan.lib.publisher.StreamPublisher$2.handleMessage(StreamPublisher.java:116)
    java.io.IOException: This InputStream was closed
        at android.os.Handler.dispatchMessage(Handler.java:102)
07-22 13:53:47.826 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at com.chillingvan.lib.encoder.MediaCodecInputStream.read(MediaCodecInputStream.java:108)
        at android.os.HandlerThread.run(HandlerThread.java:61)
        at com.chillingvan.lib.publisher.StreamPublisher$2.handleMessage(StreamPublisher.java:116)
07-22 13:53:47.827 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at android.os.Looper.loop(Looper.java:157)
        at com.chillingvan.lib.encoder.MediaCodecInputStream.readAll(MediaCodecInputStream.java:138)
07-22 13:53:47.828 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at com.chillingvan.lib.encoder.MediaCodecInputStream.readAll(MediaCodecInputStream.java:138)
07-22 13:53:47.829 32261-408/com.chillingvan.instantvideo.sample W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
        at com.chillingvan.lib.encoder.MediaCodecInputStream.read(MediaCodecInputStream.java:108)
07-22 13:53:47.830 32261-408/com.chillingvan.instantvideo.sample W/System.err: java.io.IOException: This InputStream was closed
07-22 13:53:47.856 32261-458/com.chillingvan.instantvideo.sample I/MPEG4Writer: Received total/0-length (154/0) buffers and encoded 154 frames. - Video
07-22 13:53:47.856 32261-412/com.chillingvan.instantvideo.sample D/MPEG4Writer: Video track stopping
07-22 13:53:47.858 32261-412/com.chillingvan.instantvideo.sample D/MPEG4Writer: Video track source stopping
07-22 13:53:47.859 32261-412/com.chillingvan.instantvideo.sample D/MPEG4Writer: Video track source stopped
07-22 13:53:47.859 32261-459/com.chillingvan.instantvideo.sample I/MPEG4Writer: Received total/0-length (143/0) buffers and encoded 143 frames. - Audio
07-22 13:53:47.860 32261-459/com.chillingvan.instantvideo.sample I/MPEG4Writer: Audio track drift time: 0 us
07-22 13:53:47.860 32261-412/com.chillingvan.instantvideo.sample D/MPEG4Writer: Video track stopped
    Audio track stopping
    Audio track source stopping
    Audio track source stopped
    Audio track stopped
    Duration from tracks range is [5006000, 5178978] us
    Stopping writer thread
07-22 13:53:47.861 32261-450/com.chillingvan.instantvideo.sample D/MPEG4Writer: 0 chunks are written in the last batch
07-22 13:53:47.863 32261-412/com.chillingvan.instantvideo.sample D/MPEG4Writer: Writer thread stopped
07-22 13:53:47.867 32261-412/com.chillingvan.instantvideo.sample I/MPEG4Writer: The mp4 file will not be streamable.
07-22 13:53:47.867 32261-412/com.chillingvan.instantvideo.sample D/MPEG4Writer: Video track stopping
    Audio track stopping
07-22 13:53:55.025 32261-32261/com.chillingvan.instantvideo.sample D/BaseGLTextureView: onSurfaceTextureDestroyed: 
07-22 13:54:31.132 32261-32267/com.chillingvan.instantvideo.sample I/art: Ignoring second debugger -- accepting and dropping

```

**Comment by ChillingVan** [comment]
Thanks I will check.
